name: Build Wheels

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pypa/cibuildwheel@v2
              env:
                  CIBW_BUILD: cp39-* cp310-* cp311-* cp312-*
            - uses: actions/upload-artifact@v4
